### ISSUE TITLE
Use ember-cli-dotenv with travis-ci.org

### ISSUE THREAD

**Issue by roosnic1** [fivetanley/ember-cli-dotenv#14]
Thanks for this great ember-cli addon. I was wondering if there is a possibility to use this with an automatic build system like travis-ci.org. In travis-ci.org I have the possibility to add Environment Variables which can be accessed during the build. Do you already have a best practise way how to do this?

Thanks already for your time and answer.

**Comment by fivetanley** [comment]
Hey sorry for the late delay. I get a lot of Github emails from my other projects so I miss some sometimes.

Adding environments to the project on Travis CI should be enough I think. That way they will be available in `process.env` in node. ember-cli-dotenv is really only meant as a developer convenience. 

I like to use .travis.yml to add these environment variables, or the web interface. If you have public Github projects you can use encrypted environment variables here for project contributors. https://docs.travis-ci.com/user/encryption-keys/
