### ISSUE TITLE
Generic .env file with specific .env for environments?

### ISSUE THREAD

**Issue by Dracks** [fivetanley/ember-cli-dotenv#18]
Hello, 

I'm using this plugin since some time ago, and now I see that if you have a .env file, and other for a concrete environment, it only loads the generic .env, and specific environment file don't load attributes if they are in generic .env. I think should be better if you can have a .env file with generic configuration, and the specific environment file overwrite the generic configuration. It should be change the line:

```
process.env[key] = process.env[key] || parsedObj[key]
```

for:

```
process.env[key] = parsedObj[key] || process.env[key]
```

Thanks!

**Comment by fivetanley** [comment]
It might be less confusing to have the environment file be able to take an array of files; I think having a main/other environments is fine, but having a convention of loading both can be really confusing if it's done by convention.

**Comment by Dracks** [comment]
Yes, but actually, it's loading the two files, but with priority to generic file configuration. The thing is in that case, the priority should have the specific configuration. Something more like inheritance.

**Comment by jasonmit** [comment]
Closing since there is nothing actionable here.
