### ISSUE TITLE
process.env variables are not available to config/environment.js on boot

### ISSUE THREAD

**Issue by zilkey** [fivetanley/ember-cli-dotenv#4]
I have a config/environment.js file that looks like this:

```js
module.exports = function(environment) {
  var ENV = {
    adapterURL: process.env.ADAPTER_URL,
    etc...
```

When I boot my ember app, process.env.ADAPTER_URL is not set.  Only after I change something in `config/environment.js` and force a re-compilation of that file will my app work.

The issue is that on https://github.com/fivetanley/ember-cli-dotenv/blob/master/index.js#L5 the plugin bails if there is no app.  But in order for there to be an app, it needs to load the `config/environment.js` file in your app.  So on the subsequent pass through `ember-cli-dotenv` there _is_ an app, but at this point the `environment.js` file has already been loaded.

The problem was caused by this commit: https://github.com/fivetanley/ember-cli-dotenv/commit/0909769c04e9d7128b0a5d5279b30bb7ed439226

I'm happy to submit a pull request, but I'd like some guidance.  I my understanding of the problem is correct, I think the options are:

1. Stop loading environment variables into our app's config.  Instead, just let `dotenv` load them into `process.env` and then force developers to explicitly reference `dotenv` from their environment files (which I _think_ was introduced here https://github.com/fivetanley/ember-cli-dotenv/commit/c8857314644998ba1a3b31c92c84d70e405fa6c9#diff-168726dbe96b3ce427e7fedce31bb0bcR23)
1. Force a re-compilation of the ember app's environment.js after we load our config

I vote for option 1, fwiw.  I think the problem is that we are setting keys on our app's config.

If you let me know what you think, I'd be happy to code it up!

**Comment by fivetanley** [comment]
I have no idea what the right answer is here. I'm open for anything that works! We can bump via semver so we don't break existing user's apps if they're using the carrot or tilde operator in npm. #1 sounds good to me, but I'm not sure the right hook to get it. We definitely need the `this.app` stuff so we can load the right file based off the app's path.

**Comment by zilkey** [comment]
OK - I think that PR should do it.

Basically here's what happened (correct me if I'm wrong):

- dotenv loads things into process.env (server keys + client keys)
- this package does an extra step of loading those keys directly onto our environments, so we can do the following without mucking with our config
  ```
  export default DS.ActiveModelAdapter.extend({
    host: ENV.ADAPTER_URL
  });
  ```
- the docs are out-of-date, and so lots of developers probably still have this code:
  ```
  // config/environment.js
  module.exports = function(environment){
    return {
      MY_OTHER_KEY: process.env.MY_OTHER_KEY
    }
  };
  ```
- a recent change made it so that the new, more awesome way still works, but the old set-it-yourself-in-environment-js was broken

If I got that right, then this PR should fix it.  It basically allows the old way (from the README) to work, and the new way also still works and still only loads client keys.
