### ISSUE TITLE
Travis missing ENV vars

### ISSUE THREAD

**Issue by brancusi** [fivetanley/ember-cli-dotenv#56]
Hi,

Wondering if there is something special I need to be doing when using travis.

Here's what I get even when setting the all the keys in travis.

`WARNING: [ember-cli-dotenv]: Required environment variable`

Any ideas?

**Comment by SergeAstapov** [comment]
@brancusi haven't used Travis but reading warning message looks like one (or more) of your variables is not set in `.env` file when build is running

**Comment by brancusi** [comment]
Sorry, this was because travis doesn't include untrusted sources, since this was a pull request it omitted them.
