### ISSUE TITLE
Environment not recognized correctly while using ember build --prod

### ISSUE THREAD

**Issue by davideferre** [fivetanley/ember-cli-dotenv#67]
I have different *.env* files based on environment used but with `ember build --prod` the environment used is *development* instead of *production*.
With `ember build --environment=production` all works as expected.

**Comment by jasonmit** [comment]
Lets track the upstream issue before making changes:
https://github.com/ember-cli/ember-cli/issues/8922

**Comment by davideferre** [comment]
I've proposed PR #68 .
