### ISSUE TITLE
Use for local development only

### ISSUE THREAD

**Issue by jrock2004** [fivetanley/ember-cli-dotenv#90]
So I want to use .env for local development only. But when my app runs in azure, I want it to read from the azure config settings. Now before I installed your add-on, this worked fine. But not it seems like my project needs a .env file or it breaks. Any ideas?

**Comment by jrock2004** [comment]
Anyone?

**Comment by SergeAstapov** [comment]
hi @jrock2004! Could you please elaborate what you mean by "my app runs in azure"? Do you mean you build an app with Azure as CI build agent?

> before I installed your add-on, this worked fine
how did your app pull env variables?

Sorry, need some more info to give an advice.

**Comment by jrock2004** [comment]
@SergeAstapov we run our ember app in a docker container that runs on Azure. So when installing the addon, it seems like it requires you to have a .env file or else the app does not work. I have since removed the addon all together as I did not want to cause harm to our dev/qa/prod environments.

So I guess what I am asking is, can there be some way to tell the addon to not use .env file

**Comment by fivetanley** [comment]
@jrock2004 I think the section for `environment specific use` may meet your use case. Essentially you can check if the `environment` is `production` (or use any other node code you wish) to enable or disable ember-cli-dotenv: https://github.com/fivetanley/ember-cli-dotenv#environment-specific-use

**Comment by jrock2004** [comment]
This worked. I am sorry it took so long, but finally got some time to get back to this
